### ISSUE TITLE
No such file or directory: './datasets/objects/mesh_1000/book.obj”

### ISSUE THREAD

**Issue by barrycxg** [ATAboukhadra/THOR-Net#7]
Thanks for your sharing your work. I have a problem. When I evaluate and visualize pretrained model you provided, I got an error “[Errno 2] No such file or directory: './datasets/objects/mesh_1000/book.obj”. How do I obtain the objects folder?

**Comment by ATAboukhadra** [comment]
Hi, 

You can recreate the objects by running `spherical_deformation.py` on the H2O objects available inside the **objects.zip** in the  H2O dataset. To save you time, I added the objects to the repo under **datasets/objects/mesh_1000**.

Kind regards,
Ahmed

**Comment by barrycxg** [comment]
Thanks for your reply. But I have an another question. When I run test_ho3d.sh, I encountered this error: "Error encountered while exportering file ./outputs/mesh/SM1/0092.obj:Can't open file". I can not find the folder "./outputs/mesh/SM1". 

Can you provide the folder, which is essential for me to directly visual the performance of the model.

**Comment by ATAboukhadra** [comment]
I think you just need to create the directory `./outputs/mesh/SM1` using `mkdir`. I added one line of code to create this folder if it doesn't exist.

**Comment by barrycxg** [comment]
Thanks for your reply. I successfully visual the performance of model.
